### ISSUE TITLE
No return URL

### ISSUE THREAD

**Issue by kaihendry** [rupa/sprunge#1]
x220:~$ pacman -Ql | curl -F 'sprunge=<-' http://sprunge.us
x220:~$ echo $?
0

**Comment by rupa** [comment]
Since google has instituted sharper limits for app engine stuff, sprunge is starting to run out of space. This is probably the issue here. I need to start pruning older pastes to free up some space, working on that ASAP.

Another possibility in this case is that the data you tried to post is larger than 1MB, but in that case it should report 'max size exceeded' or something

**Comment by gtmanfred** [comment]
It isn't returning urls for me today, now

**Comment by rupa** [comment]
It ran out of space. I've cleared out some stuff but it may take a while for quotas to reset. In the meantime perhaps you'll like [ix.io](http://ix.io)

**Comment by gtmanfred** [comment]
ok, thanks :-D

**Comment by jrstjohn** [comment]
This issue can be closed because sprunge automatically deletes old messages.
