### ISSUE TITLE
look mom! Without curl!

### ISSUE THREAD

**Issue by hboetes** [rupa/sprunge#5]
Since not everybody has curl installed on OpenBSD I decided to catch the curl output of a sprunge session and replicate it. The output looks identical except that my script does not work and curl does get the job done. What am I doing wrong? I hope this pasteform properly catches the input it contains ^M chars

```
# !/bin/sh
# Copyright Han Boetes hboetes@gmail.com
# Released in public domain.
# The configuration.

url=”sprunge.us”
# The code, first catch stdin into a var

stdin=$(cat)
# Discover the lenght out the input

length=$(echo “$stdin”|wc -c)
# Generate a random string

random=$(tr -dc “a-zA-Z0-9" < /dev/urandom |dd bs=12 count=1 2> /dev/null)
# nc localhost 8888 << EOF

nc $url 80 << EOF
POST / HTTP/1.1
User-Agent: feedsprunge
Host: http://$url
Accept: _/_
Content-Length: $length
Expect: 100-continue
Content-Type: multipart/form-data; boundary=$random

--$random–
Content-Disposition: form-data; name=”name”; filename=”STDIN”
Content-Type: text/foo

$stdin

--$random–
EOF
```

**Comment by ghost** [comment]
`echo "$x" | wc -c` is almost always wrong.  Not only does it include the length of an extra newline, but it is unnecessary.  The `${#x}` parameter expansion does the same thing and is cleaner.

**Comment by ghost** [comment]
That's hard to read, next time try wrapping your code in `````.

https://guides.github.com/features/mastering-markdown/

**Comment by TerrorBite** [comment]
Yes, I know this issue is four years old now, but I'm posting anyway because this might be useful to someone out there.

## Commentary

You asked what you did wrong. There are several issues with your script as posted:
- As mentioned by @joshcartwright, using `wc` to get the length can be inaccurate (plus, it calls an external util to do a job that the shell can do itself).
- You're setting the `Content-Length` header to the length of the data supplied via stdin. This is incorrect, because you're wrapping additional data (the multipart/form-data boundaries and headers) around that, so your provided `Content-Length` falls about 120 bytes short of the actual request body length.
- Only the final multipart-boundary should end in a double-dash, but both of yours do. The server will see your first boundary as the final one, and so it will interpret your request as containing zero parts.
- You've named your form field `name` when it should be `sprunge`.

## Modified Script

Since you want a script that targets OpenBSD, and your shebang indicates the script should run under `sh`, I've used only POSIX shell features in my rewrite, and (with the exception of `nc`) I have not assumed the existence of any non-POSIX utilities.

In addition to fixes for the issues above, I made some other changes, which are discussed further down.

``` sh
#!/bin/sh
# issuefive: A script to submit stdin as a paste to sprunge.us, using only netcat
# Original: Copyright Han Boetes hboetes@gmail.com
# Modified by TerrorBite (github.com/TerrorBite)
# Released in public domain.
# This script should be compatible with any POSIX-compliant shell.

# Configuration:
host="sprunge.us"

# Code
# we need nc for this to work
command -v nc >/dev/null 2>&1 || { echo "You don't have nc installed"; exit 1; }

stdin=$(cat) # Capture stdin into variable

# Generate a random string
if [ -f /proc/sys/kernel/random/uuid ]; then
    # On Linux kernels only, we can easily grab a random UUID
    boundary="------$(cat /proc/sys/kernel/random/uuid)"
elif [ -c /dev/urandom ]; then
    # Otherwise use POSIX utils to generate a UUID-like string
    boundary="------$(od -An -tx -N16 /dev/urandom | tr ' ' -)"
else
    # If urandom is unusable, just use the current seconds since epoch
    boundary="------------------MULTIPART-BOUNDARY-$(date +%s)"
fi

# Create the body of the HTML request. (Note that HTTP/1.1 uses CRLF line terminators)
# We create the body separately so we get the right length for the Content-Length header
body="--$boundary\r
Content-Disposition: form-data; name=\"sprunge\"\r
\r
$stdin\r
--$boundary--\r
"

# Send headers and body using nc (netcat)
{ nc $host 80 | tail -n 1; } << EOF
POST / HTTP/1.1\r
User-Agent: issuefive/1.0 (unix; N; $(uname -s -r -i); ${LANG-:C}; +http://github.com/rupa/sprunge/issues/5)\r
Host: $host\r
Accept: */*\r
Content-Length: ${#body}\r
Connection: close\r
Content-Type: multipart/form-data; boundary=$boundary\r
\r
$body
EOF
```

## Additional Changes

There are a few other changes I made:
- HTTP/1.1 and multipart/form-data both specify the use of CRLF-style line terminators. Even though almost every server should ignore CR according to the spec (and should therefore accept LF-only line terminators), I decided to play it safe and stick with the spec, so I explicitly added a CR before each LF.
  - Note: the actual paste data is completely unaffected by all of this, so CR characters (aka ^M characters) within the body of the paste should appear on sprunge exactly as they were in the input.
- Content-Type header in the form-data is unnecessary (`curl` doesn't send one), so I removed it. You also had it set to the nonexistent "text/foo" type.
- Instead of outputting the entire response from the server (headers and all), I used `tail` to only output the last line (i.e. the sprunge URL of the paste), which produces identical output to `curl`.
- I crafted a User-Agent string that provides a little bit of data about the system running the script (based on what a desktop browser would provide). @rupa might enjoy the analytics.
- Instead of using your method for generating a random string (searching urandom for alphanumeric characters seems messy), I went for a different method based on what's available:
  - If available, use a random UUID supplied by the kernel via `/proc`. (Linux only)
  - Otherwise, use POSIX utils to generate a UUID-like value by parsing /dev/urandom as integer data.
  - If /dev/urandom doesn't exist (unlikely), fall back to using `date` to generate a boundary value.
- I removed `Expect: 100-continue`. This header tells a server that we're going to send only headers, then wait until we receive `100 Continue` before sending the request body. This ensures that if our headers are bad, we don't end up needlessly sending our entire content to the server. However, unlike `curl`, our script checks nothing and just sends the entire request body and all, so `Expect: 100-continue` is pointless here.
  - It's possible to write this script in a way that allows it to check for the server's `100 Continue` reply, but doing this using only POSIX shell features would require creating named pipes in the filesystem in order to communicate with a background `nc` process. This seems like a lot of effort, especially when we are unlikely to benefit anyway because most pastes are relatively small.
  - If we didn't care about POSIX, we could use the coprocess features found in shells like `bash`.
- I added `Connection: close` to the headers to let the server know it can close the connection as soon as it's done with its reply. Although it does this by default, it's better to be explicit, because if the server decided to keep the connection alive, our script would hang instead of exiting.
  - We could use a construct such as `( sleep 5; kill -ALRM $$ 2>/dev/null; )&` to spawn a subshell that will send `SIGALRM` to our script after 5 seconds; we could then trap `SIGALRM` and print an appropriate timeout error before exiting. But again, this adds unnecessary complexity.

---

**Edit:** The second attempt at random string generation now uses POSIX tools and /dev/urandom instead of a BSD utility.

**Comment by hboetes** [comment]
Hi there terrorbyte. Thanks for your improvements, it really looks a lot better now.

**Comment by TerrorBite** [comment]
You are most welcome!

**Comment by rjc** [comment]
Unrelated to the matter in question but relevant to both scripts - if they're indeed in *public domain*, then, by definition, **no one** should claim any *Copyright* to them :^)

**Comment by rjc** [comment]
I forgot to mention several issues I found even before running the script:

- there is **no** mention of an `-i` option for [`uname`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/uname.html) in `POSIX` and said option does not exist on `OpenBSD`

- `${LANG-:C}` should read `${LANG:-C}`

- not an issue *per se* but I'd change `http` to `https` in GitHub issue URL - it saves a redirect

- I'd also add `-N` option to `nc`:

        -N      shutdown(2) the network socket after EOF on the input.
                Some servers require this to finish their work.
